In [1]:
import torch
import numpy as np

In [2]:
x = torch.ones(5, requires_grad= True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)

In [5]:
x = torch.randn(3, requires_grad= True)
x

tensor([-0.9909,  1.1778, -0.7459], requires_grad=True)

In [6]:
y = x + 2
y

tensor([1.0091, 3.1778, 1.2541], grad_fn=<AddBackward0>)

In [7]:
z = y*y*2
z

tensor([ 2.0365, 20.1965,  3.1457], grad_fn=<MulBackward0>)

In [8]:
z = z.mean()
z

tensor(8.4596, grad_fn=<MeanBackward0>)

In [9]:
z.backward()

x.grad

tensor([1.3454, 4.2370, 1.6722])

In [15]:
x = torch.ones(3, requires_grad=True)
y = 2*x*x + 1

y = y.sum()

y.backward()


In [16]:
x, x.grad

(tensor([1., 1., 1.], requires_grad=True), tensor([4., 4., 4.]))

In [17]:
x = torch.ones((3,4), requires_grad=True)
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], requires_grad=True)

In [18]:
x.requires_grad_(False)
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
x = torch.ones((3,4), requires_grad=True)
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], requires_grad=True)

In [21]:
y = x.detach()
y

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
with torch.no_grad():
    y = x+2
    print(y)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [34]:
import torch

x = torch.tensor(1.0)
y = torch.tensor(2.0)

x, y

(tensor(1.), tensor(2.))

In [35]:
w = torch.tensor(1.0, requires_grad= True)
w

tensor(1., requires_grad=True)

In [36]:
#forward pass
y_hat = w*x
y_hat

tensor(1., grad_fn=<MulBackward0>)

In [37]:
loss = (y_hat - y)**2
loss 

tensor(1., grad_fn=<PowBackward0>)

In [38]:
#backward pass
loss.backward()

w.grad

tensor(-2.)